language: node_js

node_js:
  - "6"

sudo: required

services:
  - docker

before_script:
  - npm install grunt-cli -g

after_success:
  - docker build -t darteaga/testing-grunt .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push darteaga/testing-grunt
