language: node_js

node_js:
  - "6"

sudo: required

services:
  - docker

before_script:
  - npm install grunt-cli -g

script:
  - grunt test

after_success:
  - VERSION=$(cat .version);
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_COMMIT_MESSAGE" =~ v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
    docker build -t darteaga/testing-grunt .;
    docker build -t darteaga/testing-grunt:$VERSION .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push darteaga/testing-grunt;
    docker push darteaga/testing-grunt:$VERSION;
    fi
